### ISSUE TITLE
Colors lost from sub process

### ISSUE THREAD

**Issue by ryardley** [google/zx#124]
## Expected Behavior
When I run a command I expect the command to forward all its output unchanged with the same colors and formatting provided from the underlying process.

## Actual Behavior
Colors are not forwarded to the output correctly. 

## Steps to Reproduce the Problem
Run any command with colored output originating from the subcommand

## Additional info

In the past I have done this by avoiding using `'data'` event listeners forwarding output and using the `stdio:'inherit'` option on spawn.

## Specifications

- Version:1.14.1
- Platform: Pop!_OS 20.10

**Comment by antonmedv** [comment]
We are using pipe method to redirect stdin.
https://github.com/google/zx/blob/ea6a800d52ffb128f546252fbba8977369343397/index.mjs#L61

**Comment by antonmedv** [comment]
Can you show an example? Code to try it out.

**Comment by ryardley** [comment]
Sure here you go: https://github.com/ryardley/zx-bug

**Comment by Dunky13** [comment]
Facing the same issue, would be nice if the colors are passed along

**Comment by alexghr** [comment]
@antonmedv this is still a problem even with zx v2.1.0. Could this issue be reopened or do you want to track it differently?

**Comment by antonmedv** [comment]
Solution:
```js
process.env.FORCE_COLOR=3
await $`...`
```

This is not "a problem". It's the current implementation. Subprocess don’t think it's a TTY and  the subprocess logic turns off colors. Usually there is a way (FORCE_COLOR=3, or similar) force subprocess logic to add colors.

**Comment by ctsstc** [comment]
Is there any reason not to have this baked in for running a command via `$` via `zx`?
If it's about not changing the environment maybe cache, change, reset it between commands?
Maybe allow an override for a command or a config override/global?
This just seems like something seen as a bug and an expected behavior that should work out of the box.

**Comment by antonmedv** [comment]
We can create it as a feature.

**Comment by alexghr** [comment]
I didn't know about `FORCE_COLORS=3`, thanks for letting me know about that @antonmedv. From reading  about it I understand it's only picked up by `chalk` (and similar color packages on npm). This would cover a big percentage of the programs that people would normally want to run through `zx`.

I'd suggest adding a note in zx's readme about supporting this, otherwise people might open issues when colors don't work out of the box for programs that don't read that environment variable (like git and grep).

Just my $0.02 :smile:

**Comment by antonmedv** [comment]
Wrote a doc on how to deal with such types of issues: https://github.com/google/zx/blob/main/docs/known-issues.md#colors-in-subprocess

**Comment by kud** [comment]
Hey,

I've tried this workaround with:

```
await $`brew uninstall ${appName} --cask`
```

and it did not work.

**Comment by ctsstc** [comment]
I noticed that `process.env.FORCE_COLOR=3` handles the top level commands, but if a command runs a command then we lose color again. Do we have to have the command also set the environment variable again? 

What about commands that spawn commands that spawn commands?! 😆

**Comment by bosens-China** [comment]
@ctsstc  Is there a solution?

**Comment by Laffery** [comment]
Still in v8.3.0, https://google.github.io/zx/known-issues#colors-in-subprocess not works for me.

I'm using `spawn` to workaround


```ts
import { spawn } from 'child_process';

spawn('npx', ['jasmine'], {
  env: { ...process.env },
  cwd: process.cwd(),
  stdio: 'inherit'
});
```
