### ISSUE TITLE
Feature suggestion: real time command output using streams

### ISSUE THREAD

**Issue by yvesnrb** [google/zx#14]
It would be really useful if one could get the output of commands in real time as they are written to stdout with a readable stream instead of awaiting for the command to exit. For example:

```
const pingStream = $.stream`ping 8.8.8.8`

pingStream.on('data', () => {
  console.log('ping wrote to stdout');
});

pingStream.on('end', () => {
  console.log('ping terminated with exit code 0');
});

pingStream.on('error', () => {
  console.log('ping terminated with an error');
});
```

**Comment by yvesnrb** [comment]
Sorry if I'm misunderstanding the way this works. I thought the promise of $`some-command` only resolved after the command exited? In this way it would not be possible to get the output of a command as it is happening before it terminated.

**Comment by antonmedv** [comment]
Yes, only then the command finished.

**Comment by catpea** [comment]
I am worried about this.

zx is a great idea and $`` wonderfully lightweight - you are wonderful!

But my feline instincts, are saying, get https://pegjs.org/ in here, and instead of shelling everything out to /bin/sh get node to take over.

This will not be lightweight, but it will unfurl what is going on between $` a | b` and grant access to all the output streams of all the commands being executed.

Now you will be able to get the stream of a's stderr for example, as it stdout into b's stdin. This is what programming is about, beautiful great things that keep you awake at night... that rustle your jimmies... that use node to make running commands even more powerful...

Instead of being clever and lightweight, which is very noble, you become a leader, you become legendary, which is even better.

I think we forget not to $`` all to often, here's Brian to remind us, what it means to hold a legendary idea:
https://www.youtube.com/watch?v=tc4ROCJYbm0&t=249s

Make flow control a first class citizen via https://www.sweetjs.org/ and instead of $` a | b` which is "what it is", allow for something even more brilliant like $ cat purr.txt | wc -l

(I leave the DSL sweetness up to you as you are excellent at it, )

Make $`commands` into real commands, not something that is just thrown at /bin/sh, but something that comes to life in node.

@yvesnrb is on the right path, we want to keep getting the data, we want to $.stream`tail -f logs/flarp` or read sockets.

pingStream.on('data', () => {
  console.log('ping wrote to stdout');
});

This is an opportunity to change the world,
you made something special, and @yvesnrb has the right idea.

**Comment by biels** [comment]
@catpea If I understand correctly are you talking about executing executables using child_process directly instead of executing sh commands?

**Comment by catpea** [comment]
@biels Yes. It would be a tree of streams that efficiently pipe data from stdout to stdin. That is what Node Streams is patterned after, pipes, pehaps even UNIX pipes. There is this wonderful opportunity here to parse the command line and make it come to life within node.

The main argument against the brilliant $\`command1 | command2\` is the same argument that is made for Node Streams, read chunk at a time, instead of cramming the whole thing into memory.

I think antonmedv did an amazing job, this is not a critique, I must admit, I think this is outside of the scope of this program.

I am simply saying parse the commands with peg.js build a child_process stream tree and allow for incredible complexity. Complexity and functionality currently obscured by node just sending a string to /bin/sh and then sitting there and waiting until a potentially massive chunk of text is returned.

So it is not just a single child_proces that wraps the entire command, it is a thing that interprets the command line, and creates a child_proces tree. It will work for simple commands like $\`tar -cvf bork.tar bork\` but also for freakishly complex things that reroute output streams, run as a daemon, respond to something like UNIX's nice(1) command, and enhance the operating system with node.

```JavaScript
await $`cat package.json | grep name`
```

Will actually start two 
child_processes one is cat and the other grep, cat will send things to grep chunk at a time, by relying on Node Streams.

The next step to this would be /bin/zxsh a zx based Bash replacement. Which will not be possible to make if we just send strings at /bin/sh

And the step after that would be using Electron as a replacement for X Windows, perhaps with https://nextapps-de.github.io/winbox/

and then antonmedv could release a https://www.linuxfromscratch.org/ called ANTONUX

And we would all end up using it.

My instinct says that

```JavaScript

let name = await $`cat package.json | grep name`;

```
obscures powerful things, that if we can get access too we can create an alternative to https://www.npmjs.com/package/pm2 alternative to Bash, and even mess around with electron as a GUI something that could potentially be as tiny as http://www.damnsmalllinux.org/

The sending a string to /bin/sh and waiting for one back obscures powerful functionality.

antonmedv your work is perfect, zx is awesome, this is not a critique, but a discussion of a potential future of this program.

You started something, that could develop legs.

Way to go!

**Comment by yvesnrb** [comment]
@catpea What you are suggesting would be quite involved to implement but I think you are on to something.

**Comment by Minigugus** [comment]
@catpea What about:

```js
await $`cat package.json`.pipe($`grep name`)
```

```js
let name = await $`cat package.json`.pipe($`grep name`);
```

The main idea is to transform `Promise<ProcessOutput>` into `DuplexStream & PromiseLike<ProcessOutput>` and rely on [`.pipe`](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options). This is significantly easier to implement than using pegjs, while increasing the *awesomeness* of pipes:

```js
const r = fs.createReadStream('file.txt');
const w = fs.createWriteStream('file.txt.gz');
await r.pipe($`gunzip`).pipe(w);
```

Pros:
 * Easy to implement (redirect duplex input to stdin and stdout to duplex output, and add a `.then` function for `await` to work)
 * User-friendly
 * Don't break the traditional `|` (``await $`cat package.json | grep name`;``)
 * Seamless integration with any node library using streams.
 * Improve support for Windows

Cons:
 * May affect performance (but the user can always fall back on | in this case)
 * Node specific feature (but `fs` and `os` are already node only)

**Comment by antonmedv** [comment]
I think this is out of the scope of the zx project. Closing.

**Comment by Minigugus** [comment]
@catpea For those looking for the pipeline feature, I made [bazx](https://deno.land/x/bazx)

```js
console.log(await collect($`find ${dir} -type f -print0`.pipe($`xargs -0 grep foo`).pipe($`wc -l`)))

// $ find /home/minigugus/UTC/GIT/PERSO/bazx/test -type f -print0 | xargs -0 grep foo | wc -l
// 3
// { success: true, code: 0, stdout: "3", stderr: "" }
```

Complete example https://github.com/Minigugus/bazx/blob/dad2564ecfa0c50f2073cdca97f9fd11053b4a15/test/showcase.js

**Comment by antonmedv** [comment]
Now zx support real time output!

**Comment by yvesnrb** [comment]
This is excellent! A lot of other great things have been added since I opened this issue as well. Thank you for bringing this library to such a high standard.
