### ISSUE TITLE
Imports not resolving well with typescript

### ISSUE THREAD

**Issue by thibault-lr** [google/zx#152]
## Expected Behavior

Can start a script with typescript files using zx

## Actual Behavior

Fails on resolution

## Steps to Reproduce the Problem

1 : `a.ts` : 

```
#!/usr/bin/env zx
import 'zx'

const a = () => { console.log('a'); }

export default a;

```

2 : b.ts 
```
#!/usr/bin/env zx
import 'zx'

import a from './a';

a();

```

3: start the script with `zx b.ts`

it produces : 
```
$ zx b.ts
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/userx/Tests/zx-test/a' imported from /Users/userx/Tests/zx-test/b.mjs
Did you mean to import ../a.js?
    at new NodeError (node:internal/errors:329:5)
    at finalizeResolution (node:internal/modules/esm/resolve:323:11)
    at moduleResolve (node:internal/modules/esm/resolve:758:10)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:869:11)
    at Loader.resolve (node:internal/modules/esm/loader:88:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:241:28)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:57:40)
    at link (node:internal/modules/esm/module_job:56:36) {
  code: 'ERR_MODULE_NOT_FOUND'
```

## Specifications

- Version: 1.14.2
- Platform: node 15.14.0

**Comment by antonmedv** [comment]
Imports not supported yet. Use ts-node or similar.

**Comment by stackptr** [comment]
> Imports not supported yet. Use ts-node or similar.

I landed here after having spent some time trying to get the `examples/typescript.ts` to work with `ts-node`. I'm using `zx` to aid in writing a script to manipulate CSVs, and so I'm using a `npm` package I'm familiar with to do a lot of the lifting. Eventually I found: https://github.com/google/zx/issues/125#issuecomment-850392517

That comment suggests that an alternative to the experimental loader is simply to use `zx`, but since imports aren't supported, as soon a user wants to pull in dependencies from `npm` it seems they'll have to use the loader approach. Some of this tooling is new to me, though.

Given all the examples in `README.md` use ``$`...` `` to invoke the shell, I'm inferring that supporting imports for `npm` packages is not a priority. If this is the case it may be worth calling out explicitly the lack of support for imports and encouraging use of shell utilities where needed.

**Comment by antonmedv** [comment]
Maybe use ts-node instead tsc in zx?

**Comment by Eggwise** [comment]
@antonmedv Do you have a working example of a ts file that imports another ts file and runs with ZX ?

**Comment by antonmedv** [comment]
Simple compile ts to js. Run js.
