### ISSUE TITLE
Why is this code throwing?

### ISSUE THREAD

**Issue by frederikhors** [google/zx#240]
## Actual Behavior

With this code it throws:

```js
#!/usr/bin/env zx

await Promise.all([$`sleep 1; echo 1`, $`sleep 2; echo 2`, $`sleep 5; echo 3`]);
```

```
$ sleep 1; echo 1
$ sleep 2; echo 2
$ sleep 5; echo 3
Error:
    at file:///C:/work/script.mjs:3:21
    exit code: 1
```

## Specifications

- Version: zx@4.2.0
- Platform: Windows 10 - Powershell-Core 7.1.4

**Comment by antonmedv** [comment]
Can’t reproduce.

**Comment by frederikhors** [comment]
What can I do?

**Comment by antonmedv** [comment]
Try to debug. Find an issue.

**Comment by frederikhors** [comment]
I don't know how. maybe it's because I'm having Git for bash installed? I'm on git version 2.33.0.windows.2.

**Comment by antonmedv** [comment]
Try WSL.

**Comment by devinrhode2** [comment]
I feel like if a terminal-related project wants to have reasonable cross-platform support, it should work with git-bash or at least cygwin. WSL is amazing, but it's a whole VM.

The quoting behavior I find very wonky and unexpected, but I'm seeing `git add $'.*ignore'` and whatever this `$'.*ignore'` bash syntax is, I just don't want it in this scenario. Just take my strings, whatever I feed into `$\`this ${string} stuff\``, and run in the terminal without modifications. Handling `.join(' ')` is cute and easy to understand. But, what if I don't want this behavior? Just my 2 cents.

I'm sure it's very nice in some situations, especially once you understand it. But as it seems the answer for windows is "WSL" that implies there is no intentional windows support.

I'm going to try execa, wish me luck :)
