### ISSUE TITLE
Removal of the test function

### ISSUE THREAD

**Issue by TheNoim** [google/zx#31]
Hi,

I want to know why the test function was removed https://github.com/google/zx/commit/4c8d6024ab212c974c0d64da8cd9fc52210e84b2 ?

Instead of this:

```javascript
if (test('-f test.js')) {
    // do stuff
}
```

I now need to write:

```javascript
try {
    await $`test -f test.js`;
    // do stuff
} catch (e) {}
```

I think this looks way more ugly. 

I understand that the test function wasn't really written well, but you could refactor it to:

```javascript
export async function test(cmd) {
    try {
        await $`test ${cmd}`;
        return true;
    } catch (e) {
        return false;
    }
}
```

**Comment by antonmedv** [comment]
Yes, deleted it mostly because it was way to off with rest of library. 

Need to think more about better implementation. For example working with $.shell, async or sync, safety, etc. 

I’m planning definitely to bring it back in future. 

Just wanted to remove current implementation of test so user will not use something what will change in future.

**Comment by TheNoim** [comment]
When do we get a similar function back? Or at least an option for the $'command' function to not throw on exit code != 0. Instead of throwing it could return null or undefined.

**Comment by antonmedv** [comment]
We need to discuss possibilities. I still didn’t found okay solution. Let’s open new issue with alternatives.

**Comment by antonmedv** [comment]
Now you can use:
```js
if (await $`[[ -d path ]]`.exitCode == 0) {
  ...
}
```
